apiVersion: v1
kind: Service
metadata:
  name: svc-ts-ms-productionmanager
  labels:
    app: svc-ts-ms-productionmanager
spec:
  selector:
    app: ts-ms-productionmanager-deployment
  type: LoadBalancer
  ports:
    - port: 6000
      protocol: TCP
      targetPort: 6000
